### ISSUE TITLE
No Lambda support??

### ISSUE THREAD

**Issue by jeveloper** [alfredxiao/jackplay#1]
Hi
Could i recommend that you look into this.
Since this is JDK8 only , lambda, streams, generics is basically essential. otherwise this is sort of pointless.

I do appreciate you building this lib.

**Comment by alfredxiao** [comment]
Admittedly, that's very good idea, but it doesn't mean the whole thing is pointless. This is related to method redefinition - which may not be the most important feature (since tracing can be more widely used); Also Also Jackplay is not a complicated tool/lib, it relies on another library to generate bytecode in runtime - in this case it is Javassist which has limitations when it comes to compliation in runtime; Lastly, in a JVM runtime (not design time, or compile time), you normally don't have facilities like Java compiler via API call that can turn a piece of source code into bytecode or byte array. If you have suggestion on this, please let me know.

**Comment by jeveloper** [comment]
Ahh, appreciate the comment.
It just seems that in the past year, more and more code is full of lambdas , stream, transformation , sorting, etc, hence this limitation would be an issue.
