### ISSUE TITLE
Empty Trace

### ISSUE THREAD

**Issue by mkrsinha5** [alfredxiao/jackplay#2]
Hey,I am trying to use Jackplay.I am trying to trace Rest Service controller method but i am getting blank screen.
FYI-I am using Tomcat 7 & JDK 8 
Will appreciate any help

**Comment by alfredxiao** [comment]
Hi, are you able to see non-blank screen when running the demo that comes together with the project codebase? It could be because of browser compatibility issue, please try use latest chrome or firefox. It it persists, please send me instructions and versions about the environment/applications you are using that could help how to replicate the issues you are seeing.

**Comment by alfredxiao** [comment]
No response from issue creator for more than two months
